server:
  port: 443

spring:
  application:
    name: fsmemory-gateway
  devtools:
    restart:
      enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

zuul:
  prefix: /gateway
  routes:
    #标识你服务的名字，
    #这里可以自己定义，一般方便和规范来讲还是跟自己服务的名字一样
    fsmemory-uim:
      #服务映射的路径，通过这路径就可以从外部访问你的服务了，
      #目的是为了不爆露你机器的IP，面向服务的路由了，给你选一个可用的出来，
      #这里zuul是自动依赖hystrix，ribbon的，不是面向单机
      path: /*/user/*
      #这里一定要是你Eureka注册中心的服务的名称，是所以这里配置serviceId因为跟eureka结合了，
      #如果单独使用zuul,那么就必须写自己机器的IP了，
      #如url:http://localhost:8080/  这样的不好就是写死IP了，万一这IP挂了，这高可用性，服务注册那套东西就用不起来了
      serviceId: fsmemory-uim

    #本地测试
    fsmemory-gateway:
      path: /test/**
      url: forward:/testMethod

feign:
  hystrix:
    enabled: false



ribbon:
  eureka:
    enabled: true
#ribbon:
#  eureka:
#    enabled: false #禁止Ribbon使用Eureka
#指定client-a的LB规则
#client-a:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    listOfServers: localhost:8080,localhost:8081
com:
  fsmemory:
    skipCheckUrls:
      - /gateway/user/login
      - /gateway/user/register
