server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #跑eureka-server的机器地址
  server:
    wait-time-in-ms-when-sync-empty: 0    #eureka获取不到对等服务实例时的等待时间
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 600

spring:
  application:
    name: eureka-server
