spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ladi
    url: jdbc:mysql://localhost:3306/fm_uim?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true                      #开启驼峰
  type-aliases-package: com.adi.fsmemory.entity
